#!/bin/sh
# $Id: synclang,v 1.4 2002/12/07 23:10:05 pasky Exp $

echo
echo Syncing other languages.
languages=`cat index.txt`
if [ -n "$languages" ]; then
	for i in $languages; do
		if [ "$i" != english ]; then
			echo -n $i" " 1>&2
			awk -f synclang.awk <$i.lng | sed 's///g' >_sync.tmp
			mv _sync.tmp $i.lng
		fi
	done
	echo
	echo Done.
fi
echo
#./gen-intl
