.\" Process this file with groff -man -Tascii elinks.1
.TH ELINKS 1 "Oct, 2001"


.SH NAME
elinks \- lynx-like alternative character mode WWW browser


.SH SYNOPSIS
.B elinks
.I "[options] URL"


.SH DESCRIPTION
.B ELinks
is a text mode WWW browser, supporting
colors, correct table rendering, background downloading, menu
driven configuration interface and slim code.
.P 
Frames are supported. You can have different file formats 
associated with external viewers. mailto: and telnet:
are supported via external clients.
.P
.I ELinks
can handle local (file://) or remote (http://, ftp:// or https://
if there's compiled-in SSL support) URLs. It has also basic support for
finger:.
.PP


.SH OPTIONS
Most options can be set in the user
interface or config file, so usually you do not need to care about them. Note
that this list is by no means complete and it is not kept up-to-date. To get
complete list of commandline options, start ELinks with parameter \f3--help\f1.

.TP
\f3-anonymous \f2<0>/<1>\f1
Restrict ELinks so that it can run on an anonymous account.
No local file browsing. No downloads. Executing of viewers
is allowed, but user can't add or modify entries in
association table.

.TP
\f3-auto-submit \f2<0>/<1>\f1
Go and submit the first form you'll stumble upon.

.TP
\f3-base-session \f2<number>\f1
ID of session (ELinks instance) which we want to clone.
This is internal ELinks option, you don't want to use it.

.TP
\f3-dump\f1
Write a plain-text version of the given HTML document to stdout.

.TP
\f3-dump-charset \f2<charset>\f1
Codepage used in dump output.

.TP
\f3-dump-width \f2<width>\f1
Width of the dump output.

.TP
\f3-eval \f2<string>\f1
Specify elinks.conf config options on the command-line:
-eval 'set protocol.file.allow_special_files = 1'

.TP
\f3-? -h -help\f1
Print usage help and exit.

.TP
\f3-lookup \f2<hostname>\f1
Make lookup for specified host.

.TP
\f3-no-connect \f2<0>/<1>\f1
Run ELinks as a separate instance - instead of connecting to
existing instance. Note that normally no runtime state files
(I mean bookmarks, history and so on) are written to the disk
with this option on - see also -touch-files.

.TP
\f3-no-home \f2<0>/<1>\f1
Don't attempt to create and/or use home rc directory (~/.elinks).

.TP
\f3-session-ring \f2<number>\f1
ID of session ring this ELinks should connect to. The ELinks
works in so-called session rings, where all instances of ELinks
are interconnected and share same state (cache, bookmarks, cookies
and so on). By default, all ELinks instances connect to session
ring 0. You can change that behaviour by this switch and form as
many session rings as you want. Obviously, if the session-ring with
this number doesn't exist yet, it's created and this ELinks instance
will become the master instance (that usually doesn't matter for you
as a user much). Note that you usually don't want to use this except
you're a developer and you want to do some testing - if you want the
ELinks instances running each one standalone, rather use -no-connect
commandline option. Also note that normally no runtime state files
are written to the disk with this option on - see also -touch-files.

.TP
\f3-source \f2<0>/<1>\f1
Write the given HTML document in source form to stdout.

.TP
\f3-stdin \f2<0>/<1>\f1
Open stdin as HTML document - it is fully equivalent to:
-eval 'set protocol.file.allow_special_files = 1' file:///dev/stdin
Use whichever suits you more ;-). Note that reading document from
stdin WORKS ONLY WHEN YOU USE -dump OR -source!! (I would like to
know why you would use -source -stdin, though ;-)

.TP
\f3-touch-files \f2<0>/<1>\f1
Set to 1 to have runtime state files (bookmarks, history, ...)
changed even when -no-connect is used; has no effect if not used
in connection with the -no-connect commandline option.

.TP
\f3-version\f1
Print ELinks version information and exit.


.SH NAVIGATION KEYS
You may optionally prefix each of this keys with a number, telling its
repeat count (how much times to do it). You can also re-bind those keys.
See \fBelinkskeys\fP(5) for complete documentation about keybindings and
more complete list of keys bound by default.
The keys you may use for navigation are:
.TP
.B PGDN
page down
.TP
.B Space
page down
.TP
.B PGUP
page up
.TP
.B b
page up
.TP
.B B
page up
.TP
.B CursorDOWN
next link/down
.TP
.B CursorUP
prev link/up
.TP
.B ^INS
copy to clipboard
.TP
.B ^C
copy to clipboard
.TP
.B INS
scroll up
.TP
.B ^P
scroll up
.TP
.B DEL
scroll down
.TP
.B ^N
scroll down
.TP
.B [
scroll left
.TP
.B ]
scroll right
.TP
.B HOME
home
.TP
.B END
end of page
.TP
.B CursorRIGHT
enter link/press button
.TP
.B ENTER
enter link/press button
.TP
.B CursorLEFT
go back
.TP
.B d
download link
.TP
.B D
download link
.TP
.B F4
edit textarea in external editor (broken)
.TP
.B ^T
edit textarea in external editor (broken)
.TP
.B /
search in the page
.TP
.B ?
search back in the page
.TP
.B n
find next match
.TP
.B N
find next match backwards
.TP
.B f
zoom actual frame
.TP
.B F
zoom actual frame
.TP
.B ^R
reload page
.TP
.B g
go to URL
.TP
.B G
go to the current URL
.TP
.B a
add a new bookmark
.TP
.B A
add a new bookmark
.TP
.B s
bookmark manager
.TP
.B S
bookmark manager
.TP
.B ^K
reload cookies from ~/.elinks/cookies
.TP
.B q
quit
.TP
.B Q
quit
.TP
.B =
document information
.TP
.B |
header information
.TP
.B \e
toggle HTML source/rendered view
.TP
.B *
toggle display of images
.TP
.B TAB
next frame
.TP
.B ESC
menu/escape
.TP
.B F9
menu
.TP
.B F10
file menu


.SH EDITING KEYS
The following keys can be used while editing a line/jumping to a URL:
.TP
.B CursorRIGHT
move right
.TP
.B CursorLEFT
move left
.TP
.B HOME
jump to the beginning
.TP
.B ^A
jump to the beginning
.TP
.B END
jump to the end
.TP
.B ^E
jump to the end
.TP
.B ^INS
copy to clipboard
.TP
.B ^B
copy to clipboard
.TP
.B ^X
cut to clipboard
.TP
.B ^V
paste from clipboard
.TP
.B ENTER
enter line
.TP
.B BACKSPACE
delete back character
.TP
.B ^H
delete back character
.TP
.B DEL
delete character
.TP
.B ^D
delete character
.TP
.B ^U
delete from beginning of the line
.TP
.B ^K
delete to the end of the line
.TP
.B ^W
auto complete line


.SH ENVIRONMENT
.TP

.IP ELINKS_CONFDIR
The location of ".elinks/" user's directory

.IP WWW_HOME
Homepage location (as in 
.B lynx
)

.IP ELINKS_XTERM, LINKS_XTERM
The command to run when selecting "File/New window" and if
.B DISPLAY
is defined (default "xterm -e")

.IP ELINKS_TWTERM, LINKS_TWTERM
The command to run when selecting "File/New window" and if
.B TWDISPLAY
is defined (default "twterm -e")

.IP SHELL
Used for "File/OS Shell" menu

.IP COMSPEC
Used for "File/OS Shell" menu in DOS/Windows


.SH FILES
.TP

.IP "~/.elinks/elinks.conf"
Per-user config file

.IP "~/.elinks/bookmarks"
Bookmarks file

.IP "~/.elinks/cookies"
Cookies file

.IP "~/.elinks/gotohist"
GoTo URL dialog history file

.IP "~/.elinks/globhist"
History file containing last 4096 URLs visited

.IP "~/.elinks/socket"
Internal ELinks socket for communication between its instances.


.SH PLATFORMS
.B ELinks
is known to work on Linux, FreeBSD, OpenBSD, Solaris, IRIX, HPUX, Digital Unix, AIX,
OS/2, BeOS and RISC OS.
Port for Win32 is in state of beta testing.


.SH BUGS
See BUGS file coming with ELinks distribution tarball for list of known bugs.
.PP
Please report any other bugs you find to
.B (E)Links mailing list
.BI <links-list@linuxfromscratch.org>.


.SH LICENSE
.B ELinks
is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.


.SH AUTHOR
.I Links
was written by 
.B Mikulas Patocka 
.BI <mikulas@artax.karlin.mff.cuni.cz>.
.I ELinks
- which is based on
.I Links
 - was written by
.B Petr Baudis
.BI <pasky@ucw.cz>.
See file 
.I AUTHORS
in the source tree for a list of people contributing to this project.
.P
The homepage of ELinks can be found at
.BI http://elinks.or.cz/
.P
This manual page was written by Peter Gervai <grin@tolna.net>,
using excerpts from a (yet?) unknown
.I Links
fan
for the Debian GNU/Linux system (but may be used by others).
Contributions from Francis A. Holop. Extended, clarified
and made more up-to-date by Petr Baudis <pasky@ucw.cz>.
Updated by Zas <zas at norz.org>.

.SH "SEE ALSO"
.BR elinkskeys (5),
.BR links (1),
.BR lynx (1),
.BR w3m (1),
.BR wget (1)
