.\" Process this file with groff -man -Tascii elinkskeys.5
.TH ELINKSKEYS 5 "May, 2002"


.SH NAME
elinkskeys \- ELinks WWW browser key bindings


.SH SYNOPSIS
.B ~/.elinks/user.cfg


.SH DESCRIPTION
Key bindings for 
.I elinks
should be placed in a file called \fB~/.elinks/user.cfg\fP.  This file
will be read from but not written to, so you may put comments in
there.

Key binding statements are of the form:
.IP
bind \fIkeymap keystroke action\fP
.P
where:

.TP
.B keymap
is
.IR main ,
.IR edit ,
or
.IR menu .

.TP
.B keystroke
is a case sensitive key, which you can prefix with \fICtrl-\fP or
\fIAlt-\fP.  \fICtrl-\fP must be followed by an uppercase key.  See
below for a list of valid keys.

.TP
.B action
is what the key should do.  The actions available are dependent on the
keymap, and are listed separately below.

.P
All words/strings may all be quoted "like so".  Backslashes are escape
characters, even if not between quotes.  Lines beginning with a hash
character (#) are comments.

Keys can be unbound using the
.B unbind
statement.
.IP
unbind \fIkeymap keystroke\fP
.P
It may be of use if you accidentally type a key often.


.SH KEYS

Valid keys are: alphanumeric characters, punctuation, Enter,
Backspace, Tab, Escape, Left, Right, Up, Down, Insert, Delete, Home,
End, PageUp, PageDown, F1 to F12.

Some keys will need to be quoted or escaped.  For example, space can
be written as " " (quote space quote), and the quote itself as \\"
(backslash quote).  Backslash can be written as \\\\\ (double
backslash).

.\" " <-- for emacs' benefit

.SH MAIN KEYMAP ACTIONS
The
.I main
keymap is used for general browsing.

.TP
.B add-bookmark
Open a dialog box to add a new bookmark.

.TP
.B back
Return to the previous page.

.TP
.B bookmark-manager
Open the bookmark manager dialog.

.TP
.B cookies-load
??? Reload cookies file.  (ELinks only)
[pasky, shouldn't this be load-cookies?]

.TP
.B copy-clipboard
Copy the current link to the clipboard.

.TP
.B document-info
Show some information about the current page.

.TP
.B down
Move cursor downwards.

.TP
.B download
Start downloading the current link. 

.TP
.B end
Go to the end of the page.

.TP
.B enter
Follow the current link.

.TP
.B file-menu
Open the File menu.

.TP
.B find-next
Find the next occurrence of the current search text.

.TP
.B find-next-back
Find the next occurrence of the current search text, in reverse.

.TP
.B goto-url
Open a "Go to URL" dialog box.

.TP
.B goto-url-current
Open a "Go to URL" dialog box containing the current URL.

.TP
.B goto-url-current-link
Open a "Go to URL" dialog box containing the current link.

.TP
.B header-info
Show the current page header information.

.TP
.B home
Go to the start of the page.

.TP
.B link-menu
Activate the contextual link menu.

.TP
.B lua-console
Open a Lua Console dialog box.  Only available if Lua scripting
support has been compiled in (Links-Lua and ELinks).

.TP
.B menu
Activate the menu.

.TP
.B next-frame
Move to the next frame.

.TP
.B open-new-window
Open a new instace of \fIELinks\fP in a new window.

.TP
.B open-link-in-new-window
Open the current link in a new instance of \fIELinks\fP in a new
window.

.TP
.B page-down
Move downwards by a page.

.TP
.B page-up
Move upwards by a page.

.TP
.B paste-clipboard
Paste text from the clipboard.

.TP
.B previous-frame
Move to the previous frame.

.TP
.B quit
Open a quit confirmation dialog box.

.TP
.B really-quit
Quit without confirmation.

.TP
.B reload
Reload the current page.

.TP
.B scroll-down
Scroll the viewing window downwards.

.TP
.B scroll-left
Scroll the viewing window to the left.

.TP
.B scroll-right
Scroll the viewing window to the right.

.TP
.B scroll-up
Scroll the viewing window upwards.

.TP
.B search
Search for some text.

.TP
.B search-back
Search for some text, in reverse.

.TP
.B toggle-display-images
Toggle whether to display links to images.

.TP
.B toggle-display-tables
Toggle whether to render tables.

.TP
.B toggle-html-plain
Toggles between rendering the current page as HTML or plaintext.

.TP
.B unback
Go forwards in unhistory.  (ELinks only)

.TP
.B up
Move cursor upwards.

.TP
.B view-image
View the image under the cursor.

.TP
.B zoom-frame
Show the current frame using the entire screen.


.SH EDIT KEYMAP ACTIONS

The
.I edit
keymap is used for editing text fields.

.TP
.B up
.TP
.B down
.TP
.B left
.TP
.B right
.TP
.B home
.TP
.B end
.TP
.B backspace
.TP
.B delete
.TP
.B kill-to-bol
Delete text from cursor to beginning of line.
.TP
.B kill-to-eol
Delete text from cursor to end of line.
.TP
.B auto-complete
.TP
.B enter
.TP
.B copy-clipboard
.TP
.B cut-clipboard
.TP
.B paste-clipboard
.TP
.B edit
Edit the current textarea in an external text editor.  (ELinks only)


.SH MENU KEYMAP ACTIONS

The
.I menu
keymap is used for navigating menus.

.TP
.B left
.TP
.B right
.TP
.B up
.TP
.B down
.TP
.B home
.TP
.B  end
.TP
.B  page-up
.TP
.B page-down


.SH DEFAULT BINDINGS

The default bindings are shown below.  Any bindings in
.I user.cfg
will override these.  This list is given as an example, and may not be
up to date.

.nf
bind main PageDown      page-down
bind main " "           page-down
bind main Ctrl-F        page-down
bind main PageUp        page-up
bind main b             page-up
bind main B             page-up
bind main Ctrl-B        page-up
bind main Down          down
bind main Up            up
bind main Ctrl-Insert   copy-clipboard
bind main Ctrl-C        copy-clipboard
bind main Insert        scroll-up
bind main Ctrl-P        scroll-up
bind main Delete        scroll-down
bind main Ctrl-N        scroll-down
bind main [             scroll-left
bind main ]             scroll-right
bind main Home          home
bind main Ctrl-A        home
bind main End           end
bind main Ctrl-E        end
bind main Right         enter
bind main Enter         enter
bind main Left          back
bind main d             download
bind main D             download
bind main /             search
bind main ?             search-back
bind main n             find-next
bind main N             find-next-back
bind main f             zoom-frame
bind main F             zoom-frame
bind main Ctrl-R        reload
bind main g             goto-url
bind main G             goto-url-current
bind main a             add-bookmark
bind main A             add-bookmark
bind main s             bookmark-manager
bind main S             bookmark-manager
bind main q             quit
bind main Q             really-quit
bind main =             document-info
bind main |             header-info
bind main \\\\            toggle-html-plain
bind main *             toggle-display-images
bind main Tab           next-frame
bind main Escape        menu
bind main F9            menu
bind main F10           file-menu

bind edit Left          left
bind edit Right         right
bind edit Home          home
bind edit Ctrl-A        home
bind edit Up            up
bind edit Down          down
bind edit End           end
bind edit Ctrl-E        end
bind edit Ctrl-Insert   copy-clipboard
bind edit Ctrl-B        copy-clipboard
bind edit Ctrl-X        cut-clipboard
bind edit Ctrl-V        paste-clipboard
bind edit Enter         enter
bind edit Backspace     backspace
bind edit Ctrl-H        backspace
bind edit Delete        delete
bind edit Ctrl-D        delete
bind edit Ctrl-U        kill-to-bol
bind edit Ctrl-K        kill-to-eol
bind edit Ctrl-W        auto-complete

bind menu Left          left
bind menu Right         right
bind menu Home          home
bind menu Ctrl-A        home
bind menu Up            up
bind menu Down          down
bind menu End           end
bind menu Ctrl-E        end
bind menu Enter         enter
bind menu PageDown      page-down
bind menu Ctrl-F        page-down
bind menu PageUp        page-up
bind menu Ctrl-B        page-up

# ELinks only
bind main l             link-menu
bind main L             link-menu
bind main u             unback
bind main U             unback
bind main Ctrl-K        cookies-load
bind edit F4            edit
bind edit Ctrl-T        edit

# Links-Lua and ELinks
bind main ,             lua-console


.SH FILES

.TR
.B /etc/elinks/elinks.cfg
Site-wide configuration file.

.TR
.B ~/.elinks/user.cfg
Per-user configuration file, loaded after site-wide configuration.


.SH AUTHOR

This manual page was finally written by Peter Wang (one and a half
years after writing the binding code), using excerpts by David
Mediavilla.  You can thank Petr Baudis for the subtle requests for
documentation. Updated by Zas.


.SH "SEE ALSO"
.BR elinks (1)
