#!/bin/sh
#
# Simple shell scripts to insert style sheet in all html files in a directory,
# directory is passed as the first argument to the program
#
# $Id: installcss,v 1.2 2002/12/30 15:57:01 jonas Exp $

cp style.css $1

cd $1

for i in `ls *.html`; do
    cat $i | sed 's/<\/head>/<link rel="STYLESHEET" type="text\/css" href="style.css"><\/head>/' > tmp
    mv tmp $i
done

cd -
