#!/bin/sh
#
# Generate the elinkskeys(5) manpage.
# Copyright (c) Jonas Fonseca <fonseca@diku.dk>, 2005
#
# $Id: make-elinkskeys-manpage,v 1.3 2005/05/14 21:29:36 jonas Exp $

# FIXME:
#
# - You may prefix each of these keys with a number, telling its repeat
# count (how many times to do it). You can also re-bind keys, see
# elinkskeys(5) for documentation and a more complete list of keys  bound by
# default. 
#
# - The following keys can be used while editing a line/jumping to a URL

DOCTYPE=$(echo "$1" | sed 's/elinks.//' | sed 's/.txt//')
KBDBIND=$2

ACTINFO="$(grep ACT_ $KBDBIND | grep '^[[:space:]]{')"
DEFAULTS="$(echo $ACTINFO | grep -v DACT | grep -v '{ \"')"
ACTIONS="$(echo $ACTINFO | grep DAC)"

link()
{
	target="$1"; shift

	[ "$1" ] && name="$@"
	case "$DOCTYPE" in
	man)
		echo "$name <$target>"
		;;
	html)
		echo "link:$target[$name]"
		;;
	esac
}

man()
{
	target="$1"
	section="$2"

	case "$DOCTYPE" in
	man)
		echo "\`$target($section)\`"
		;;
	html)
		echo "link:$target.html[\`$target($section)\`]"
		;;
	esac
}

print_keymap_actions()
{
	keymap=$1

	grep ACT_ $KBDBIND | grep '^[[:space:]]{' | grep -v DISABLED | grep DACT | grep -i ACT_$keymap \
	| while read entry
	do
		action=$(echo "$entry" | sed 's/.*{ "\([^"]*\)".*/\1/')
		caption=$(echo "$entry" | sed 's/.*N_("\(.*\)").*/\1/')

		[ "$action" = "none" ] && continue

		echo
		echo "$action::"
		echo "	$caption."
	done
}

print_keymap_defaults()
{
	keymap=$1

	grep ACT_ $KBDBIND | grep '^[[:space:]]{' | grep -v DACT | grep -v '{ "' | grep -i ACT_$keymap \
	| while read entry
	do
		entry=$(echo "$entry" | sed 's/.*{ //' | sed 's/ }.*//')
		key=$(echo "$entry" | sed "s/\(KBD_[^,]*\|'.*'\),.*/\1/")
		modifier=$(echo "$entry" | sed "s/.*,.*KBD_MOD_\([A-Z_]*\),.*/\1/")
		action=$(echo "$entry" | sed "s/.*,.*\(ACT_[A-Z_]*\).*/\1/")

		case "$key" in
			KBD_*)
				key=$(grep $key $KBDBIND | grep '^[[:space:]]{' | grep '{ "' | sed 's/.*"\([^"]*\)".*/\1/')
				;;
			"' '")
				key="Space"
				;;
			*)
				key=$(echo "$key" | sed "s/^'\(.*\)'/\1/" | sed "s/'/\\\\'/")
				;;
		esac

		case "$modifier" in
			ALT) 	modifier="Alt-"		;;
			CTRL)	modifier="Ctrl-"	;;
			*)		modifier=""			;;
		esac

		action=$(grep "$action," $KBDBIND | grep -v DISABLED | grep DACT | sed "s/.*\"\([^\"]*\)\".*N_(\"\(.*\)\").*/\2 ('\1')/")
		echo
		echo "'$modifier$key'::"
		echo "	$action"
	done
}

cat << __END__
elinkskeys(5)
=============

NAME
----
elinkskeys - keybindings for ELinks

SYNOPSIS
--------
Information on how to configure keybinding and overview of the default
keybindings.

DESCRIPTION
-----------

Key binding for elinks should be placed in a file called
~/.elinks/elinks.conf. Note that any information regarding their
format/structure may not be up-to-date. If you will discover that, please
feed us with a patch.

Key binding statements are of the form:

	bind <keymap> <keystroke> = <action>

where:

<keymap>::
	is 'main', 'edit', or 'menu'.

<keystroke>::
	is a case sensitive key, which you can prefix with 'Ctrl-' or 'Alt-'.
	'Ctrl-' must be followed by an uppercase key. See below for a list of
	valid keys.

<action>::

	is what the key should do. The actions available are dependent on the
	keymap, and are listed separately below.

All words/strings may all be quoted "like so". Backslashes are escape
characters, even if not between quotes.	Lines beginning with a hash
character (\`#\`) are comments.

Keys can be unbound just by binding them to the special 'none' action. It
may be of use if you accidentally type a key often.

EXAMPLE BINDINGS
----------------

Some sample keybindings:

	bind "main" "v" = "view-image"
	bind "main" "l" = "jump-to-link"
	bind "main" "L" = "link-menu"
	bind "main" "F10" = "file-menu"
	bind "main" "F9" = "menu"
	bind "main" "Escape" = "menu"
	bind "edit" "Ctrl-R" = "auto-complete-unambiguous"
	bind "edit" "Ctrl-W" = "auto-complete"
	bind "edit" "Ctrl-K" = "kill-to-eol"
	bind "menu" "Ctrl-B" = "page-up"
	bind "menu" "PageUp" = "page-up"
	bind "menu" "Ctrl-F" = "page-down"
	bind "menu" "PageDown" = "page-down"
	# ELinks with Lua support
	bind "main" ","	= "lua-console"

KEYS
----

Valid keys are: alphanumeric characters, punctuation, 'Enter', 'Backspace',
'Tab', 'Escape', 'Left', 'Right', 'Up', 'Down', 'Insert', 'Delete', 'Home',
'End', 'PageUp', 'PageDown', 'F1' to 'F12'.

Some keys will need to be quoted or escaped. For example, space can be
written	as  \`" "\` (quote space quote), and the quote itself as \\"
(backslash quote).  Backslash can be written as \\\\ (double backslash).

MAIN KEYMAP ACTIONS
~~~~~~~~~~~~~~~~~~~

The main keymap is used for general browsing.

$(print_keymap_actions main)

EDIT KEYMAP ACTIONS
~~~~~~~~~~~~~~~~~~~

The edit keymap is used for editing text fields.

$(print_keymap_actions edit)

MENU KEYMAP ACTIONS
~~~~~~~~~~~~~~~~~~~

The menu keymap is used for navigating menus.

$(print_keymap_actions menu)

DEFAULT BINDINGS
----------------

The default bindings are shown below. Any bindings in
\`~/.elinks/elinks.conf\` will override these.

MAIN KEYS
~~~~~~~~~

$(print_keymap_defaults main)

EDIT KEYS
~~~~~~~~~

$(print_keymap_defaults edit)

MENU KEYS
~~~~~~~~~

$(print_keymap_defaults menu)

AUTHOR
------

This manual page was finally written by Peter Wang (one and a half years
after writing the binding code), using excerpts by David Mediavilla. You can
thank Petr Baudis for the subtle requests for documentation. Updated by Zas.
Moved to asciidoc format and cleaned up by Jonas Fonseca.

SEE ALSO
--------

$(man elinks 1), \`elinks.conf(5)\`

__END__

# vim: tabstop=4 shiftwidth=4 textwidth=76
