## $Id: Makefile.doc,v 1.2 2003/06/09 22:11:42 jonas Exp $

# Assumes the variabel $(DOCBUILDDIR) is set by the includers

SUFFIXES = .xml .1 .5

HTMLDOCTOOL	 = @HTMLDOCTOOL@
MANDOCTOOL	 = @MANDOCTOOL@

%.html: %.xml
	$(HTMLDOCTOOL) -o $(DOCBUILDDIR) $<

%.1: %.1.xml
	$(MANDOCTOOL) -o $(DOCBUILDDIR)/man/man1 $<

%.5: %.5.xml
	$(MANDOCTOOL) -o $(DOCBUILDDIR)/man/man5 $<
