## $Id: Makefile.doc,v 1.6 2003/06/10 23:47:29 jonas Exp $

SUFFIXES = .xml .1 .5
HTMLDOCTOOL = @HTMLDOCTOOL@
MANDOCTOOL = @MANDOCTOOL@

DOCBUILDDIR = $(top_srcdir)/doc/

%.html: %.xml
	$(mkinstalldirs) $(DOCBUILDDIR)/html
	test -n "$(HTMLDOCTOOL)" && $(HTMLDOCTOOL) -o $(DOCBUILDDIR)/html/`basename $< .xml` $<

%.1: %.1.xml
	$(mkinstalldirs) $(DOCBUILDDIR)/man/man1
	test -n "$(MANDOCTOOL)" && $(MANDOCTOOL) -o $(DOCBUILDDIR)/man/man1 $<

%.5: %.5.xml
	$(mkinstalldirs) $(DOCBUILDDIR)/man/man5
	test -n "$(MANDOCTOOL)" && $(MANDOCTOOL) -o $(DOCBUILDDIR)/man/man5 $<

manpages-html: $(manpages_HTMLFORMAT)
manpages-man: $(manpages_MANFORMAT)
manpages: manpages-man manpages-html

book-html: $(book_HTMLFORMAT)
book: $(book_HTMLFORMAT)
